# Generated by Django 4.1.1 on 2022-10-18 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadministrador', models.AutoField(db_column='idAdministrador', primary_key=True, serialize=False)),
                ('idaplicativo', models.IntegerField(blank=True, db_column='idAplicativo', null=True)),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('contrasenia', models.CharField(max_length=32)),
                ('nombres', models.CharField(max_length=125)),
                ('apellidos', models.CharField(max_length=125)),
                ('idpais', models.IntegerField(blank=True, db_column='idPais', null=True)),
                ('celular', models.CharField(max_length=18, unique=True)),
                ('cedula', models.CharField(max_length=18, unique=True)),
                ('correo', models.CharField(max_length=125, unique=True)),
                ('hangouts', models.CharField(max_length=125)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='')),
                ('idadministradorregistro', models.IntegerField(blank=True, db_column='idAdministradorRegistro', null=True)),
                ('idadministradoredito', models.IntegerField(blank=True, db_column='idAdministradorEdito', null=True)),
                ('bloqueadomensaje', models.CharField(blank=True, db_column='bloqueadoMensaje', max_length=400, null=True)),
                ('bloqueado', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_reactivacion', models.DateTimeField(blank=True, null=True)),
                ('mensajereactivacion', models.CharField(blank=True, db_column='mensajeReactivacion', max_length=400, null=True)),
                ('tiposangre', models.CharField(blank=True, db_column='tipoSangre', max_length=6, null=True)),
                ('cambiarclave', models.IntegerField(blank=True, db_column='cambiarClave', null=True)),
                ('clavetemporal', models.CharField(blank=True, db_column='claveTemporal', max_length=5, null=True)),
                ('fecha_cambio_clave', models.DateTimeField(blank=True, null=True)),
                ('fecha_recupero_clave', models.DateTimeField(blank=True, null=True)),
                ('idtipoidentificacion', models.IntegerField(blank=True, db_column='idTipoIdentificacion', null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserEntidad',
            fields=[
                ('id_user_entidad', models.AutoField(db_column='id_user_entidad', primary_key=True, serialize=False)),
                ('id_entidad', models.ForeignKey(db_column='id_entidad', on_delete=django.db.models.deletion.DO_NOTHING, to='entidad.entidad')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_entidad',
                'managed': True,
                'unique_together': {('id_user',)},
            },
        ),
    ]
