# Generated by Django 4.1.1 on 2022-10-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('moneda', models.CharField(max_length=5)),
                ('simbolo', models.CharField(blank=True, max_length=45, null=True)),
                ('referencia', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
                ('pais', models.IntegerField()),
            ],
            options={
                'db_table': 'moneda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.AutoField(db_column='idPais', primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=45, unique=True)),
                ('acronimo', models.CharField(max_length=4, unique=True)),
                ('codigoarea', models.CharField(db_column='codigoArea', max_length=5, unique=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('idadministradorregistro', models.IntegerField(db_column='idAdministradorRegistro')),
                ('idadministradoractualizo', models.IntegerField(blank=True, db_column='idAdministradorActualizo', null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.TextField()),
                ('limite', models.TextField(blank=True, null=True)),
                ('idmoneda', models.IntegerField(blank=True, db_column='idMoneda', null=True)),
                ('min_digitos_cedula', models.IntegerField(blank=True, null=True)),
                ('max_digitos_cedula', models.IntegerField(blank=True, null=True)),
                ('min_digitos_celular', models.IntegerField(blank=True, null=True)),
                ('max_digitos_celular', models.IntegerField(blank=True, null=True)),
                ('validar_cedula', models.IntegerField(blank=True, null=True)),
                ('numericos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.AutoField(db_column='idCiudad', primary_key=True, serialize=False)),
                ('ciudad', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=45, null=True, unique=True)),
                ('acronimo', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=10)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('limite', models.TextField(blank=True, null=True)),
                ('eliminado', models.IntegerField()),
                ('comentario', models.CharField(max_length=500)),
                ('zonahoraria', models.CharField(blank=True, db_column='zonaHoraria', max_length=6, null=True)),
                ('type', models.CharField(max_length=100)),
                ('id_padre', models.IntegerField()),
                ('pais_idpais', models.ForeignKey(db_column='pais_idPais', on_delete=django.db.models.deletion.DO_NOTHING, to='pais.pais')),
            ],
            options={
                'db_table': 'ciudad',
                'managed': True,
            },
        ),
    ]
