# Generated by Django 4.1.1 on 2022-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.AutoField(db_column='idPerfil', primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=500)),
                ('eliminado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilAdministrador',
            fields=[
                ('idadministrador', models.IntegerField(db_column='idAdministrador', primary_key=True, serialize=False)),
                ('idperfil', models.IntegerField(db_column='idPerfil')),
                ('idadministradorregistro', models.IntegerField(db_column='idAdministradorRegistro')),
                ('idadministradorhabilito', models.IntegerField(blank=True, db_column='idAdministradorHabilito', null=True)),
                ('idadministradordeshabilito', models.IntegerField(blank=True, db_column='idAdministradorDeshabilito', null=True)),
                ('fecha_habilito', models.DateTimeField(blank=True, null=True)),
                ('fecha_deshabilito', models.DateTimeField(blank=True, null=True)),
                ('idadministradoractualizo', models.IntegerField(blank=True, db_column='idAdministradorActualizo', null=True)),
                ('fecha_actualizo', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.TextField()),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'perfil_administrador',
                'managed': False,
            },
        ),
    ]
