# Generated by Django 4.1.1 on 2022-10-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadministrador', models.AutoField(db_column='idAdministrador', primary_key=True, serialize=False)),
                ('idaplicativo', models.IntegerField(blank=True, db_column='idAplicativo', null=True)),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('contrasenia', models.CharField(max_length=32)),
                ('nombres', models.CharField(max_length=125)),
                ('apellidos', models.CharField(max_length=125)),
                ('idpais', models.IntegerField(blank=True, db_column='idPais', null=True)),
                ('celular', models.CharField(max_length=18, unique=True)),
                ('cedula', models.CharField(max_length=18, unique=True)),
                ('correo', models.CharField(max_length=125, unique=True)),
                ('hangouts', models.CharField(max_length=125)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='')),
                ('idadministradorregistro', models.IntegerField(blank=True, db_column='idAdministradorRegistro', null=True)),
                ('idadministradoredito', models.IntegerField(blank=True, db_column='idAdministradorEdito', null=True)),
                ('bloqueadomensaje', models.CharField(blank=True, db_column='bloqueadoMensaje', max_length=400, null=True)),
                ('bloqueado', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_reactivacion', models.DateTimeField(blank=True, null=True)),
                ('mensajereactivacion', models.CharField(blank=True, db_column='mensajeReactivacion', max_length=400, null=True)),
                ('tiposangre', models.CharField(blank=True, db_column='tipoSangre', max_length=6, null=True)),
                ('cambiarclave', models.IntegerField(blank=True, db_column='cambiarClave', null=True)),
                ('clavetemporal', models.CharField(blank=True, db_column='claveTemporal', max_length=5, null=True)),
                ('fecha_cambio_clave', models.DateTimeField(blank=True, null=True)),
                ('fecha_recupero_clave', models.DateTimeField(blank=True, null=True)),
                ('idtipoidentificacion', models.IntegerField(blank=True, db_column='idTipoIdentificacion', null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogsSystemFintech',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tabla', models.CharField(max_length=45)),
                ('data', models.TextField(db_collation='utf8mb4_bin')),
                ('tipo', models.CharField(max_length=45)),
                ('idadministrador', models.CharField(db_column='idAdministrador', max_length=45)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs_system_fintech',
                'managed': True,
            },
        ),
    ]
