# Generated by Django 4.1.1 on 2022-10-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_userentidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentidad',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
    ]
