# Generated by Django 4.1.1 on 2022-10-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('idmodulo', models.IntegerField(db_column='idModulo', primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=100)),
                ('icono', models.ImageField(upload_to='')),
                ('vista', models.CharField(max_length=45)),
                ('orden', models.IntegerField()),
                ('identificativo', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('idaplicativo', models.IntegerField(blank=True, db_column='idAplicativo', null=True)),
                ('idadministradorregistro', models.IntegerField(db_column='idAdministradorRegistro')),
                ('idadministradoractualizo', models.IntegerField(blank=True, db_column='idAdministradorActualizo', null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('id_servicio', models.IntegerField(blank=True, null=True)),
                ('vistapath', models.CharField(db_column='vistaPath', max_length=95)),
            ],
            options={
                'db_table': 'modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuloPerfil',
            fields=[
                ('idmodulo', models.IntegerField(db_column='idModulo', primary_key=True, serialize=False)),
                ('idperfil', models.IntegerField(db_column='idPerfil')),
            ],
            options={
                'db_table': 'modulo_perfil',
                'managed': True,
                'unique_together': {('idmodulo', 'idperfil')},
            },
        ),
        migrations.CreateModel(
            name='Moduloadministrador',
            fields=[
                ('idadministrador', models.IntegerField(db_column='idAdministrador', primary_key=True, serialize=False)),
                ('idmodulo', models.IntegerField(db_column='idModulo')),
                ('inicio', models.IntegerField()),
                ('leer', models.IntegerField()),
                ('crear', models.IntegerField()),
                ('editar', models.IntegerField()),
                ('eliminar', models.IntegerField()),
                ('fecha_lectura', models.DateTimeField()),
                ('fecha_crear', models.DateTimeField(blank=True, null=True)),
                ('fecha_editar', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminar', models.DateTimeField(blank=True, null=True)),
                ('idadministradorregistro', models.IntegerField(db_column='idAdministradorRegistro')),
                ('idadministradoractualizo', models.IntegerField(blank=True, db_column='idAdministradorActualizo', null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.IntegerField()),
            ],
            options={
                'db_table': 'moduloadministrador',
                'managed': True,
                'unique_together': {('idadministrador', 'idmodulo')},
            },
        ),
    ]
