# Generated by Django 4.1.1 on 2022-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listanegra',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
    ]
