# Generated by Django 4.1.1 on 2022-10-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteBot',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('recipienteid', models.IntegerField(db_column='recipienteId', unique=True)),
                ('senderid', models.IntegerField(db_column='senderId', unique=True)),
                ('nombres', models.CharField(blank=True, max_length=45, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('alias', models.CharField(blank=True, max_length=45, null=True)),
                ('token', models.CharField(blank=True, max_length=45, null=True)),
                ('medio', models.CharField(blank=True, max_length=45, null=True)),
                ('parametro', models.IntegerField(blank=True, null=True)),
                ('recurso', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('entidad', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('dato_extra', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('recurso_url', models.URLField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente_bot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClienteBotHasEntidad',
            fields=[
                ('cliente_bot_idcliente', models.OneToOneField(db_column='cliente_bot_idCliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cliente.clientebot')),
                ('eliminado', models.IntegerField()),
                ('entidad_identidad', models.ForeignKey(db_column='entidad_idEntidad', on_delete=django.db.models.deletion.DO_NOTHING, to='entidad.entidad')),
            ],
            options={
                'db_table': 'cliente_bot_has_entidad',
                'managed': True,
                'unique_together': {('cliente_bot_idcliente', 'entidad_identidad')},
            },
        ),
    ]
