# Generated by Django 4.1.1 on 2022-10-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionesCampo',
            fields=[
                ('idopcion', models.AutoField(db_column='idOpcion', primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
                ('idcampo_opcion', models.IntegerField(db_column='idCampo_opcion')),
            ],
            options={
                'db_table': 'opciones_campo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposCampos',
            fields=[
                ('idtipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('descripcion', models.CharField(max_length=45)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
            ],
            options={
                'db_table': 'tipos_campos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CamposPersonalizadosNuevaCuenta',
            fields=[
                ('idcampo', models.AutoField(db_column='idCampo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=55, null=True)),
                ('identificador', models.CharField(max_length=55)),
                ('requerido', models.IntegerField()),
                ('validador', models.IntegerField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
                ('nopaste', models.IntegerField()),
                ('tipo', models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='campos.tiposcampos')),
            ],
            options={
                'db_table': 'campos_personalizados_nueva_cuenta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CamposPersonalizadosEntidad',
            fields=[
                ('entidad_identidad', models.OneToOneField(db_column='entidad_idEntidad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='entidad.entidad')),
                ('habilitado', models.IntegerField()),
                ('campos_personalizados_nueva_cuenta_idcampo', models.ForeignKey(db_column='campos_personalizados_nueva_cuenta_idCampo', on_delete=django.db.models.deletion.DO_NOTHING, to='campos.campospersonalizadosnuevacuenta')),
            ],
            options={
                'db_table': 'campos_personalizados_entidad',
                'managed': True,
                'unique_together': {('entidad_identidad', 'campos_personalizados_nueva_cuenta_idcampo')},
            },
        ),
    ]
