# Generated by Django 4.1.1 on 2022-10-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0002_alter_campospersonalizadosnuevacuenta_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campospersonalizadosentidad',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
    ]
