# Generated by Django 4.1.1 on 2022-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduloadministrador',
            name='eliminar',
        ),
        migrations.AddField(
            model_name='moduloperfil',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
    ]
