# Generated by Django 4.1.1 on 2022-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pais',
            name='eliminado',
            field=models.IntegerField(default=0),
        ),
    ]
