# Generated by Django 4.1.1 on 2022-10-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('idplan', models.AutoField(db_column='idPlan', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('acronimo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('costo', models.CharField(max_length=45)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
            ],
            options={
                'db_table': 'plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanContrato',
            fields=[
                ('plan_idplan', models.IntegerField(db_column='plan_idPlan', primary_key=True, serialize=False)),
                ('contrato_idcontrato', models.IntegerField(db_column='contrato_idContrato')),
                ('contrato_entidad_identidad', models.IntegerField(db_column='contrato_entidad_idEntidad')),
            ],
            options={
                'db_table': 'plan_contrato',
                'managed': True,
                'unique_together': {('plan_idplan', 'contrato_idcontrato', 'contrato_entidad_identidad')},
            },
        ),
        migrations.CreateModel(
            name='DetallePlan',
            fields=[
                ('plan_idplan', models.OneToOneField(db_column='plan_idPlan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='plan.plan')),
                ('modulo_idmodulo', models.IntegerField(db_column='modulo_idModulo')),
                ('eliminado', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_plan',
                'managed': True,
                'unique_together': {('plan_idplan', 'modulo_idmodulo')},
            },
        ),
    ]
