# Generated by Django 4.1.1 on 2022-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogosErrores',
            fields=[
                ('idmsg_error', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
            ],
            options={
                'db_table': 'catalogos_errores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('idmensaje', models.AutoField(db_column='idMensaje', primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
                ('identidad', models.IntegerField(db_column='idEntidad')),
            ],
            options={
                'db_table': 'mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensajeErrores',
            fields=[
                ('idmensaje_error', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=250)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('eliminado', models.IntegerField()),
                ('id_entidad', models.IntegerField()),
                ('id_error', models.IntegerField()),
            ],
            options={
                'db_table': 'mensaje_errores',
                'managed': False,
            },
        ),
    ]
